### ISSUE TITLE
app.dock.hide() doesn't work on Windows 11

### ISSUE THREAD

**Issue by Zero2Infinity** [DmytroVasin/DrawPen#17]
I successfully built and ran your DrawPen app on my Windows machine with one blocker line - `app.dock.hide() in index.js:234` 
After reading SO - https://stackoverflow.com/questions/46364167/what-is-the-equivalent-for-app-dock-hide, I commented the above line, and it hides the app icon from the tray area.

# Configurations:
- OS: Windows 11 (x64)
- Node: 22.6.0
- NPM: 10.9.0

This is less important if you do not care about cross-platform during the initial period. 
I wanted to share that your code works on Windows and you might attract users coming from other platforms that like what you have built so far.

Best wishes!

**Comment by DmytroVasin** [comment]
Hi @Zero2Infinity,

Thank you for your feedback and for taking the time to test my DrawPen app! 
I’m glad to hear that you were able to build and run it successfully on your Windows machine. 

I am still developing the app, so some features may not work :( 
FYI: I have not launched it on Windows at all :D 

I re-pushed the new version with several fixes for Windows

Thanks!
