### ISSUE TITLE
Feature request Highlighter

### ISSUE THREAD

**Issue by spaceVast** [DmytroVasin/DrawPen#20]
tool is nice with the hot key Ctrl shift A , hope u add a highlighter option

**Comment by DmytroVasin** [comment]
I do not think that I can add "highlighter" :( 


Dev details: 
For now, I do not know how to resolve issue with overlapping semi-transparent lines 

![Screenshot 2024-11-30 at 10 01 52](https://github.com/user-attachments/assets/832e99ba-a8c8-433e-8b8c-e6b1b3b39569)

**Comment by DmytroVasin** [comment]
I've added Highlighter 

1 Year later :)
