### ISSUE TITLE
Linux multi-screen support

### ISSUE THREAD

**Issue by daveprowse** [DmytroVasin/DrawPen#21]
First off, this program has REAL potential. Great work so far! 
I would primarily be using this with Linux. Currently, in a multi-monitor setup, the program can't figure out which monitor to draw on in Linux (Debian) and can't lock to a particular monitor. 
A toggle for turning on and off would be excellent.

**Comment by DmytroVasin** [comment]
Thank you for bringing this to my attention!

This project is still in its early stages, so it’s not fully ready yet. However, I’ve already identified and addressed several issues related to multi-monitor support on Linux, including the ability to determine and lock onto a specific monitor.

I’m aiming to stabilize the application within the next month, and by then, multi-monitor setups should work seamlessly. Thanks for your patience and support!

**Comment by DmytroVasin** [comment]
Fixed
